// Minimal typed schema (not generated by `supabase gen types`).
// Extend when adding columns.

export type Role = 'admin' | 'hq_viewer' | 'campus_manager';

export interface Database {
  public: {
    Tables: {
      campuses: {
        Row: { id: number; name: string; type: 'direct' | 'franchise'; display_order: number };
        Insert: { id: number; name: string; type: 'direct' | 'franchise'; display_order: number };
        Update: Partial<Database['public']['Tables']['campuses']['Insert']>;
        Relationships: [];
      };
      profiles: {
        Row: { id: string; email: string; full_name: string | null; role: Role; campus_id: number | null; created_at: string };
        Insert: { id: string; email: string; full_name?: string | null; role: Role; campus_id?: number | null };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
        Relationships: [];
      };
      student_snapshots: {
        Row: { id: string; base_date: string; filename: string; uploaded_by: string; uploaded_at: string; row_count: number; storage_path: string; is_active: boolean };
        Insert: { id?: string; base_date: string; filename: string; uploaded_by: string; row_count: number; storage_path: string; is_active?: boolean };
        Update: Partial<Database['public']['Tables']['student_snapshots']['Insert']>;
        Relationships: [];
      };
      students: {
        Row: { snapshot_id: string; student_code: string; campus_raw: string; campus_id: number | null; name: string; teacher: string | null; status: string; grade: string | null; level: string | null; phase: string | null; raw: unknown };
        Insert: Database['public']['Tables']['students']['Row'];
        Update: Partial<Database['public']['Tables']['students']['Row']>;
        Relationships: [];
      };
      log_uploads: {
        Row: { id: string; filename: string; uploaded_by: string; uploaded_at: string; period_start_auto: string; period_end_auto: string; row_count: number; storage_path: string };
        Insert: { id?: string; filename: string; uploaded_by: string; period_start_auto: string; period_end_auto: string; row_count: number; storage_path: string };
        Update: Partial<Database['public']['Tables']['log_uploads']['Insert']>;
        Relationships: [];
      };
      access_logs: {
        Row: { id: number; log_upload_id: string; campus_raw: string; teacher_name: string | null; student_name: string | null; student_code: string; access_datetime: string };
        Insert: Omit<Database['public']['Tables']['access_logs']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['access_logs']['Insert']>;
        Relationships: [];
      };
      reports: {
        Row: {
          id: string; student_snapshot_id: string; log_upload_id: string;
          period_start: string; period_end: string; exclude_upper_levels: boolean;
          created_by: string; created_at: string; data: unknown; xlsx_path: string | null;
        };
        Insert: {
          id?: string;
          student_snapshot_id: string;
          log_upload_id: string;
          period_start: string;
          period_end: string;
          exclude_upper_levels: boolean;
          created_by: string;
          data: unknown;
          xlsx_path?: string | null;
        };
        Update: Partial<Database['public']['Tables']['reports']['Row']>;
        Relationships: [];
      };
      report_downloads: {
        Row: { id: number; report_id: string; user_id: string; downloaded_at: string };
        Insert: Omit<Database['public']['Tables']['report_downloads']['Row'], 'id' | 'downloaded_at'>;
        Update: Partial<Database['public']['Tables']['report_downloads']['Row']>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
